/**
 * Shared test fixtures — a small set of raw "DB-shaped" food rows covering every
 * role, region and allergen the logic modules branch on.
 */

export const RAW_FOODS = [
  {
    id: 'chicken', name: 'Chicken Breast', category: 'protein',
    serving_amount: 100, serving_unit: 'g',
    calories: 165, protein: 31, carbs: 0, fats: 3.6, fiber: 0, sugar: 0, sodium: 74,
    iron: 1, calcium: 15, magnesium: 29, potassium: 256, zinc: 1, selenium: 22,
    folate: 4, vitamin_b12: 0.3, vitamin_d: 0.1, vitamin_a: 21, vitamin_c: 0, iodine: 7,
    glycemic_index: 0, allergens: [], dietary_tags: ['gluten_free', 'dairy_free'],
    regions: ['universal'],
  },
  {
    id: 'salmon', name: 'Salmon', category: 'protein',
    serving_amount: 100, serving_unit: 'g',
    calories: 208, protein: 20, carbs: 0, fats: 13, fiber: 0, sugar: 0, sodium: 59,
    iron: 0.3, calcium: 12, magnesium: 30, potassium: 363, zinc: 0.6, selenium: 36,
    folate: 25, vitamin_b12: 3.2, vitamin_d: 11, vitamin_a: 12, vitamin_c: 0, iodine: 30,
    glycemic_index: 0, allergens: ['fish'], dietary_tags: ['gluten_free', 'dairy_free'],
    regions: ['universal'],
  },
  {
    id: 'lentils', name: 'Lentils (cooked)', category: 'legumes',
    serving_amount: 100, serving_unit: 'g',
    calories: 116, protein: 9, carbs: 20, fats: 0.4, fiber: 8, sugar: 1.8, sodium: 2,
    iron: 3.3, calcium: 19, magnesium: 36, potassium: 369, zinc: 1.3, selenium: 3,
    folate: 181, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 0, vitamin_c: 1.5, iodine: 3,
    glycemic_index: 32, allergens: [], dietary_tags: ['vegan', 'vegetarian', 'gluten_free'],
    regions: ['indian', 'mediterranean'],
  },
  {
    id: 'paneer', name: 'Paneer', category: 'dairy',
    serving_amount: 100, serving_unit: 'g',
    calories: 265, protein: 18, carbs: 3.6, fats: 21, fiber: 0, sugar: 3.6, sodium: 22,
    iron: 0.2, calcium: 480, magnesium: 22, potassium: 100, zinc: 1.9, selenium: 15,
    folate: 5, vitamin_b12: 1.1, vitamin_d: 0.3, vitamin_a: 190, vitamin_c: 0, iodine: 40,
    glycemic_index: 27, allergens: ['dairy'], dietary_tags: ['vegetarian', 'gluten_free'],
    regions: ['indian'],
  },
  {
    id: 'brown-rice', name: 'Brown Rice (cooked)', category: 'grain',
    serving_amount: 100, serving_unit: 'g',
    calories: 112, protein: 2.6, carbs: 23.5, fats: 0.9, fiber: 1.8, sugar: 0.4, sodium: 5,
    iron: 0.5, calcium: 10, magnesium: 43, potassium: 43, zinc: 0.6, selenium: 10,
    folate: 4, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 0, vitamin_c: 0, iodine: 2,
    glycemic_index: 68, allergens: [], dietary_tags: ['vegan', 'vegetarian', 'gluten_free'],
    regions: ['universal'],
  },
  {
    id: 'white-bread', name: 'White Bread', category: 'grain',
    serving_amount: 100, serving_unit: 'g',
    calories: 265, protein: 9, carbs: 49, fats: 3.2, fiber: 2.7, sugar: 5, sodium: 491,
    iron: 3.6, calcium: 260, magnesium: 25, potassium: 115, zinc: 0.8, selenium: 28,
    folate: 120, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 0, vitamin_c: 0, iodine: 5,
    glycemic_index: 75, allergens: ['gluten', 'wheat'], dietary_tags: ['vegan', 'vegetarian'],
    regions: ['western'],
  },
  {
    id: 'oats', name: 'Rolled Oats', category: 'grain',
    serving_amount: 100, serving_unit: 'g',
    calories: 379, protein: 13, carbs: 67, fats: 6.5, fiber: 10, sugar: 1, sodium: 6,
    iron: 4.7, calcium: 52, magnesium: 138, potassium: 362, zinc: 3, selenium: 28,
    folate: 32, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 0, vitamin_c: 0, iodine: 4,
    glycemic_index: 55, allergens: [], dietary_tags: ['vegan', 'vegetarian'],
    regions: ['universal'],
  },
  {
    id: 'spinach', name: 'Spinach', category: 'vegetable',
    serving_amount: 100, serving_unit: 'g',
    calories: 23, protein: 2.9, carbs: 3.6, fats: 0.4, fiber: 2.2, sugar: 0.4, sodium: 79,
    iron: 2.7, calcium: 99, magnesium: 79, potassium: 558, zinc: 0.5, selenium: 1,
    folate: 194, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 469, vitamin_c: 28, iodine: 12,
    glycemic_index: 15, allergens: [], dietary_tags: ['vegan', 'vegetarian', 'gluten_free'],
    regions: ['universal'],
  },
  {
    id: 'broccoli', name: 'Broccoli', category: 'vegetable',
    serving_amount: 100, serving_unit: 'g',
    calories: 34, protein: 2.8, carbs: 7, fats: 0.4, fiber: 2.6, sugar: 1.7, sodium: 33,
    iron: 0.7, calcium: 47, magnesium: 21, potassium: 316, zinc: 0.4, selenium: 2.5,
    folate: 63, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 31, vitamin_c: 89, iodine: 15,
    glycemic_index: 15, allergens: [], dietary_tags: ['vegan', 'vegetarian', 'gluten_free'],
    regions: ['universal'],
  },
  {
    id: 'almonds', name: 'Almonds', category: 'nuts',
    serving_amount: 100, serving_unit: 'g',
    calories: 579, protein: 21, carbs: 22, fats: 50, fiber: 12.5, sugar: 4.4, sodium: 1,
    iron: 3.7, calcium: 269, magnesium: 270, potassium: 733, zinc: 3.1, selenium: 4,
    folate: 44, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 0, vitamin_c: 0, iodine: 2,
    glycemic_index: 0, allergens: ['nuts', 'tree_nuts'], dietary_tags: ['vegan', 'vegetarian'],
    regions: ['universal'],
  },
  {
    id: 'olive-oil', name: 'Olive Oil', category: 'oils',
    serving_amount: 100, serving_unit: 'g',
    calories: 884, protein: 0, carbs: 0, fats: 100, fiber: 0, sugar: 0, sodium: 2,
    iron: 0.6, calcium: 1, magnesium: 0, potassium: 1, zinc: 0, selenium: 0,
    folate: 0, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 0, vitamin_c: 0, iodine: 0,
    glycemic_index: 0, allergens: [], dietary_tags: ['vegan', 'vegetarian', 'gluten_free'],
    regions: ['universal', 'mediterranean'],
  },
  {
    id: 'greek-yogurt', name: 'Greek Yogurt', category: 'dairy',
    serving_amount: 100, serving_unit: 'g',
    calories: 59, protein: 10, carbs: 3.6, fats: 0.4, fiber: 0, sugar: 3.2, sodium: 36,
    iron: 0, calcium: 110, magnesium: 11, potassium: 141, zinc: 0.5, selenium: 9.7,
    folate: 7, vitamin_b12: 0.75, vitamin_d: 0, vitamin_a: 27, vitamin_c: 0, iodine: 50,
    glycemic_index: 11, allergens: ['dairy'], dietary_tags: ['vegetarian', 'gluten_free'],
    regions: ['universal'],
  },
  {
    id: 'banana', name: 'Banana', category: 'fruit',
    serving_amount: 100, serving_unit: 'g',
    calories: 89, protein: 1.1, carbs: 23, fats: 0.3, fiber: 2.6, sugar: 12, sodium: 1,
    iron: 0.3, calcium: 5, magnesium: 27, potassium: 358, zinc: 0.2, selenium: 1,
    folate: 20, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 3, vitamin_c: 8.7, iodine: 2,
    glycemic_index: 51, allergens: [], dietary_tags: ['vegan', 'vegetarian', 'gluten_free'],
    regions: ['universal'],
  },
  {
    id: 'roti', name: 'Whole Wheat Roti', category: 'grain',
    serving_amount: 100, serving_unit: 'g',
    calories: 297, protein: 10, carbs: 46, fats: 7.5, fiber: 6, sugar: 2, sodium: 250,
    iron: 3, calcium: 30, magnesium: 90, potassium: 200, zinc: 1.7, selenium: 30,
    folate: 40, vitamin_b12: 0, vitamin_d: 0, vitamin_a: 0, vitamin_c: 0, iodine: 5,
    glycemic_index: 62, allergens: ['gluten', 'wheat'], dietary_tags: ['vegan', 'vegetarian'],
    regions: ['indian'],
  },
];

export const BASE_PROFILE = {
  weightKg: 70,
  heightCm: 175,
  age: 30,
  sex: 'male',
  jobActivity: 'light',
  sessionsPerWeek: 4,
  avgMinutes: 60,
  modalities: ['strength'],
  intensity: 'moderate',
  goal: 'maintain',
  goalRate: 'moderate',
};
